### ISSUE TITLE
IOError: [Errno 36] File name too long for .cu and .log

### ISSUE THREAD

**Issue by jvw1954** [thomasvs/morituri#111]
"...
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 41, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/usr/lib/python2.7/dist-packages/morituri/rip/main.py", line 45, in main
    ret = c.parse(argv)
  File "/usr/lib/python2.7/dist-packages/morituri/rip/main.py", line 123, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/dist-packages/morituri/rip/cd.py", line 159, in do
    self.doCommand()
  File "/usr/lib/python2.7/dist-packages/morituri/rip/cd.py", line 450, in doCommand
    self.program.writeCue(discName)
  File "/usr/lib/python2.7/dist-packages/morituri/common/program.py", line 735, in writeCue
    handle = open(cuePath, 'w')
IOError: [Errno 36] File name too long: u'/var/music/Jennifer Vyvyan, James Bowman, Charles Brett, Peter Pears, Mary Wells, Ian Partridge, John Shirley-Quirk, Owen Brannigan, Norma Burrowes, Alfreda Hodgson, Ambrosian Opera Chorus, English Chamber Orchestra/Henry Purcell 1659-1695 - The Fairy Queen (Disc 1 of 2)/Jennifer Vyvyan, James Bowman, Charles Brett, Peter Pears, Mary Wells, Ian Partridge, John Shirley-Quirk, Owen Brannigan, Norma Burrowes, Alfreda Hodgson, Ambrosian Opera Chorus, English Chamber Orchestra - Henry Purcell 1659-1695 - The Fairy Queen (Disc 1 of 2).cue'"

**Comment by thomasvs** [comment]
On 03/01/2015 12:40 PM, jvw1954 wrote:
>
> "...
> Traceback (most recent call last):
> File "/usr/local/bin/rip", line 41, in
> sys.exit(main.main(sys.argv[1:]))
> File "/usr/lib/python2.7/dist-packages/morituri/rip/main.py", line 45, 
> in main
> ret = c.parse(argv)
> File "/usr/lib/python2.7/dist-packages/morituri/rip/main.py", line 
> 123, in parse
> logcommand.LogCommand.parse(self, argv)
> File 
> "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", 
> line 401, in parse
> return self.subCommands[command].parse(args[1:])
> File 
> "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", 
> line 401, in parse
> return self.subCommands[command].parse(args[1:])
> File 
> "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", 
> line 363, in parse
> ret = self.do(args)
> File "/usr/lib/python2.7/dist-packages/morituri/rip/cd.py", line 159, 
> in do
> self.doCommand()
> File "/usr/lib/python2.7/dist-packages/morituri/rip/cd.py", line 450, 
> in doCommand
> self.program.writeCue(discName)
> File "/usr/lib/python2.7/dist-packages/morituri/common/program.py", 
> line 735, in writeCue
> handle = open(cuePath, 'w')
> IOError: [Errno 36] File name too long: u'/var/music/Jennifer Vyvyan, 
> James Bowman, Charles Brett, Peter Pears, Mary Wells, Ian Partridge, 
> John Shirley-Quirk, Owen Brannigan, Norma Burrowes, Alfreda Hodgson, 
> Ambrosian Opera Chorus, English Chamber Orchestra/Henry Purcell 
> 1659-1695 - The Fairy Queen (Disc 1 of 2)/Jennifer Vyvyan, James 
> Bowman, Charles Brett, Peter Pears, Mary Wells, Ian Partridge, John 
> Shirley-Quirk, Owen Brannigan, Norma Burrowes, Alfreda Hodgson, 
> Ambrosian Opera Chorus, English Chamber Orchestra - Henry Purcell 
> 1659-1695 - The Fairy Queen (Disc 1 of 2).cue'"
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/thomasvs/morituri/issues/111>.
>
Yeah, that does look too long.  Which filesystem?

Thomas

-- 

- You can't just tell a falcon when to hunt.
- Actually you can... there's a whole sport built around it.
Falconry.

GStreamer - bringing multimedia to your desktop
http://gstreamer.freedesktop.org/

**Comment by jvw1954** [comment]
ext3 or ext4 via nfs
