### ISSUE TITLE
AssertionError when multiple release records

### ISSUE THREAD

**Issue by storrgie** [thomasvs/morituri#122]
Reporting Crash

```
[morituri-uninstalled] [agd@eros Downloads]$ rip cd rip
WARNING: using default offset 0.
Install pycdio and run 'rip offset find' to detect your drive's offset.
Checking device /dev/sr0
eject: CD-ROM tray close command failed: Input/output error
CDDB disc id: 020c3114                        
MusicBrainz disc id qg4Jq4x2sUa_8fR1mFxfgsWIXZs-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+20+234232+150+9515+17410+25842+33652+41449+67170+73600+81407+86828+90967+96772+103117+106701+113964+120238+126656+150606+166285+212053&tracks=20&id=qg4Jq4x2sUa_8fR1mFxfgsWIXZs-
Disc duration: 00:52:01.093, 20 audio tracks

Matching releases:

Artist  : Thomas Newman
Title   : Meet Joe Black
Duration: 00:51:59.993
URL     : https://musicbrainz.org/release/015f38c8-99e9-43ff-8b0d-6afd65779f3c
Release : 015f38c8-99e9-43ff-8b0d-6afd65779f3c
Type    : Soundtrack

Artist  : Thomas Newman
Title   : Meet Joe Black
Duration: 00:51:59.993
URL     : https://musicbrainz.org/release/194a8d4b-947b-3105-8c54-e8b16216a30f
Release : 194a8d4b-947b-3105-8c54-e8b16216a30f
Type    : Soundtrack

Artist  : Thomas Newman
Title   : Meet Joe Black
Duration: 00:51:59.993
URL     : https://musicbrainz.org/release/434fa572-4feb-3e58-a60d-af229bc085a0
Release : 434fa572-4feb-3e58-a60d-af229bc085a0
Type    : Soundtrack

Traceback (most recent call last):                 
  File "/home/agd/Programs/morituri/bin/rip", line 41, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/home/agd/Programs/morituri/morituri/rip/main.py", line 45, in main
    ret = c.parse(argv)
  File "/home/agd/Programs/morituri/morituri/rip/main.py", line 123, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/home/agd/Programs/morituri/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/home/agd/Programs/morituri/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/home/agd/Programs/morituri/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/home/agd/Programs/morituri/morituri/rip/cd.py", line 115, in do
    self.itable.getCDDBDiscId(), self.ittoc.getCDDBDiscId())
AssertionError: full table's id 1d191714 differs from toc id 020c3114
```

**Comment by storrgie** [comment]
forgot to add:
```
[morituri-uninstalled] [agd@eros morituri]$ git reflog 
fb98e7c HEAD@{0}: clone: from git@github.com:thomasvs/morituri.git
```

**Comment by Freso** [comment]
Duplicate of #99.
