### ISSUE TITLE
Long artisit name list issue

### ISSUE THREAD

**Issue by brendan-pike** [thomasvs/morituri#136]
$ rip cd rip
Using configured read offset 6
Checking device /dev/sr0
CDDB disc id: d90a1110                        
MusicBrainz disc id qdLaQgpV3mr1xTq38Z5Z3ZcUm9E-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+16+193435+187+13017+26020+35887+48772+60025+72310+84207+95052+107172+118965+131950+144392+156217+166565+177685&tracks=16&id=qdLaQgpV3mr1xTq38Z5Z3ZcUm9E-
Disc duration: 00:42:56.640, 16 audio tracks

Matching releases:

Artist  : The Shangri-Las, Diana Ross & The Supremes, Mary Wells, The Dixie Cups, The Shirelles, The Velvelettes, Martha Reeves and The Vandellas & The Angels
Title   : Girl Groups: The Story of a Sound
Duration: 00:42:56.636
URL     : https://musicbrainz.org/release/e41cdb59-6395-4014-a569-5c98b0debf00
Release : e41cdb59-6395-4014-a569-5c98b0debf00
Type    : None

Creating output directory /home/bedlore/unknown/The Shangri-Las, Diana Ross & The Supremes, Mary Wells, The Dixie Cups, The Shirelles, The Velvelettes, Martha Reeves and The Vandellas & The Angels - Girl Groups - The Story of a Sound
Traceback (most recent call last):
  File "/usr/local/bin/rip", line 41, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/site-packages/morituri/rip/main.py", line 45, in main
    ret = c.parse(argv)
  File "/usr/local/lib/python2.7/site-packages/morituri/rip/main.py", line 123, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/local/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/local/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/local/lib/python2.7/site-packages/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/local/lib/python2.7/site-packages/morituri/rip/cd.py", line 160, in do
    self.doCommand()
  File "/usr/local/lib/python2.7/site-packages/morituri/rip/cd.py", line 310, in doCommand
    os.makedirs(dirname)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/home/bedlore/unknown/The Shangri-Las, Diana Ross & The Supremes, Mary Wells, The Dixie Cups, The Shirelles, The Velvelettes, Martha Reeves and The Vandellas & The Angels - Girl Groups - The Story of a Sound'

**Comment by thomasvs** [comment]
That is indeed a really long artist name.  What filesystem is this 
trying to save to?

T

**Comment by brendan-pike** [comment]
Hi Thomas

Slow reply sorry. I run on ext4.

Model: ATA INTEL SSDSA2CW12 (scsi)
Disk /dev/sdc: 120GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos

Number  Start   End     Size    Type      File system  Flags
  1      1049kB  10.0GB  10.0GB  primary                boot
  2      10.0GB  120GB   110GB   extended
  5      10.0GB  120GB   110GB   logical   ext4

Thanks
Brendan
