### ISSUE TITLE
ZeroDivisionError in program/cdparanoia.py's getTrackQuality()

### ISSUE THREAD

**Issue by Freso** [thomasvs/morituri#46]
The output from the ripping session:

```
MusicBrainz lookup URL http://mm.musicbrainz.org/bare/cdlookup.html?toc=1+1+332955+150&tracks=1&id=hdJUmiZ9Vnnvl_xjfHLFUgpUbd0-
Disc duration: 01:13:57.400, 1 audio tracks

Matching releases:

Artist  : [nature sounds]
Title   : Ocean Waves at Dawn
Duration: 01:13:57.400
URL     : http://musicbrainz.org/release/1e053f42-b001-42bb-98a0-2e4cb49bec47
Release : 1e053f42-b001-42bb-98a0-2e4cb49bec47
Type    : Album

** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Creating output directory [nature sounds] - Ocean Waves at Dawn (1997) [FLAC]
Ripping track 1 of 1: 01. [nature sounds] - Ocean Waves at Dawn.flac
Ripping track 1 of 1 (try 2): 01. [nature sounds] - Ocean Waves at Dawn.flac
Traceback (most recent call last):                 
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 309, in _read
    self._done()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 383, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 199, in getTrackQuality
    return min(frames * 2.0 / reads, 1.0)
ZeroDivisionError: float division by zero
Ripping track 1 of 1 (try 3): 01. [nature sounds] - Ocean Waves at Dawn.flac
Traceback (most recent call last):                 
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 309, in _read
    self._done()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 383, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 199, in getTrackQuality
    return min(frames * 2.0 / reads, 1.0)
ZeroDivisionError: float division by zero
Ripping track 1 of 1 (try 4): 01. [nature sounds] - Ocean Waves at Dawn.flac
Traceback (most recent call last):                 
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 309, in _read
    self._done()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 383, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 199, in getTrackQuality
    return min(frames * 2.0 / reads, 1.0)
ZeroDivisionError: float division by zero
Ripping track 1 of 1 (try 5): 01. [nature sounds] - Ocean Waves at Dawn.flac
Traceback (most recent call last):                 
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 511, in c
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 309, in _read
    self._done()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 383, in _done
    self.quality = self._parser.getTrackQuality()
  File "/usr/lib/python2.7/site-packages/morituri/program/cdparanoia.py", line 199, in getTrackQuality
    return min(frames * 2.0 / reads, 1.0)
ZeroDivisionError: float division by zero
ERROR [15360] "rip"                            rip               sep 29 23:45:44      Giving up on track 1 after 5 times (morituri/rip/cd.py:385)
Giving up on track 1 after 5 times
```

Perhaps because it only has the one track? I've ripped other one-track albums before though...

**Comment by jmtd** [comment]
I've hit this error with a 25-track CD, attempting to rip track 1. https://gist.github.com/jmtd/41450be5406b175a69b1
