### ISSUE TITLE
Unable to rip game audio (Quake 1/2)

### ISSUE THREAD

**Issue by monreal** [thomasvs/morituri#61]
I just tried to rip the audio of my Quake 1 and 2 CDs, in both cases I get an error like this:

Checking device /dev/sr0
CDDB disc id: b90fea0b  
Traceback (most recent call last):
  File "/home/mimox/local/morituri-master/bin/rip", line 41, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/home/mimox/local/morituri-master/morituri/rip/main.py", line 45, in main
    ret = c.parse(argv)
  File "/home/mimox/local/morituri-master/morituri/rip/main.py", line 123, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/home/mimox/local/morituri-master/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/home/mimox/local/morituri-master/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/home/mimox/local/morituri-master/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/home/mimox/local/morituri-master/morituri/rip/cd.py", line 84, in do
    self.mbdiscid = self.ittoc.getMusicBrainzDiscId()
  File "/home/mimox/local/morituri-master/morituri/image/table.py", line 335, in getMusicBrainzDiscId
    values = self._getMusicBrainzValues()
  File "/home/mimox/local/morituri-master/morituri/image/table.py", line 450, in _getMusicBrainzValues
    assert not self.tracks[-1].audio
AssertionError

**Comment by Xylemon** [comment]
I am getting this too, no help?

**Comment by thomasvs** [comment]
I don't have a CD like this handy.  I'd need one for working on this.

**Comment by jmtd** [comment]
Just hit this myself with v0.2.3-17-g135b2f7 / 135b2f7bf27721177e3aeb1d26403f1b29116599. @thomasvs , I could probably provide you with a BIN/CUE for this CD for testing purposes. There's a bunch of images [here](http://dk.toastednet.org/FPS_Legends/quake.html) which I can try and see if this issue occurs with.

For the time being, this might be useful

```
$ cdrdao read-toc  outfile
Cdrdao version 1.2.3 - (C) Andreas Mueller <andreas@daneb.de>
/dev/sr0: HL-DT-ST DVDRAM GU90N Rev: LU20
Using driver: Generic SCSI-3/MMC - Version 2.0 (options 0x0000)

Reading toc data...

Track   Mode    Flags  Start                Length
------------------------------------------------------------
 1      DATA    4      00:00:00(     0)     03:43:09( 16734)
 2      AUDIO   1      03:43:09( 16734)     05:08:45( 23145)
 3      AUDIO   1      08:51:54( 39879)     02:26:01( 10951)
 4      AUDIO   1      11:17:55( 50830)     08:20:19( 37519)
 5      AUDIO   1      19:37:74( 88349)     06:05:29( 27404)
 6      AUDIO   1      25:43:28(115753)     07:24:44( 33344)
 7      AUDIO   1      33:07:72(149097)     08:38:17( 38867)
 8      AUDIO   1      41:46:14(187964)     05:35:69( 25194)
 9      AUDIO   1      47:22:08(213158)     06:28:69( 29169)
10      AUDIO   1      53:51:02(242327)     03:32:42( 15942)
11      AUDIO   1      57:23:44(258269)     05:15:31( 23656)
Leadout AUDIO   0      62:39:00(281925)

PQ sub-channel reading (data track) is supported, data format is BCD.
Raw P-W sub-channel reading (data track) is supported.
PQ sub-channel reading (audio track) is supported, data format is BCD.
Raw P-W sub-channel reading (audio track) is supported.
```
