### ISSUE TITLE
Ripping fails with TaskException

### ISSUE THREAD

**Issue by dietrmat** [thomasvs/morituri#88]
Hi,

ripping fails for me with a TaskException, running latest git version on Ubuntu 14.04.
You can find the debug log here:
https://www.dropbox.com/s/bi13sl7tnh5ffte/morituri.log.gz

If need further infomation, feel free to contact me.
And thank you for this great piece of software.

**Comment by hrehfeld** [comment]
for me too, in a virtual archlinux box, latest git and community package

$ rip offset find
Checking device /dev/cdrom
Traceback (most recent call last):  
  File "/usr/bin/rip", line 41, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 45, in main
    ret = c.parse(argv)
  File "/usr/lib/python2.7/site-packages/morituri/rip/main.py", line 123, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/site-packages/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/site-packages/morituri/rip/offset.py", line 106, in do
    runner.run(t)
  File "/usr/lib/python2.7/site-packages/morituri/extern/task/task.py", line 490, in run
    raise TaskException(task.exception, message=msg)
morituri.extern.task.task.TaskException: (AssertionError('This Table Index should be a TOC',), 'exception AssertionError at /usr/lib/python2.7/site-packages/morituri/program/cdrdao.py:424: done(): This Table Index should be a TOC')
