### ISSUE TITLE
AssertionError: full table's id de12a711 differs from toc id d30fee10

### ISSUE THREAD

**Issue by Freso** [thomasvs/morituri#99]
See output at http://sprunge.us/OKVA

I am guessing morituri is balking due to the datatrack on MusicBrainz, a new feature that went live on Monday (see also #98), but it might be something completely different.

**Comment by lpar** [comment]
Same problem here.

```
Traceback (most recent call last):                 
  File "/usr/bin/rip", line 41, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/usr/lib/python2.7/dist-packages/morituri/rip/main.py", line 45, in main
    ret = c.parse(argv)
  File "/usr/lib/python2.7/dist-packages/morituri/rip/main.py", line 123, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/dist-packages/morituri/rip/cd.py", line 115, in do
    self.itable.getCDDBDiscId(), self.ittoc.getCDDBDiscId())
AssertionError: full table's id 3f2bc314 differs from toc id 3712b714
```

**Comment by butonic** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/rip", line 41, in <module>
    sys.exit(main.main(sys.argv[1:]))
  File "/usr/lib/python2.7/dist-packages/morituri/rip/main.py", line 45, in main
    ret = c.parse(argv)
  File "/usr/lib/python2.7/dist-packages/morituri/rip/main.py", line 123, in parse
    logcommand.LogCommand.parse(self, argv)
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 401, in parse
    return self.subCommands[command].parse(args[1:])
  File "/usr/lib/python2.7/dist-packages/morituri/extern/command/command.py", line 363, in parse
    ret = self.do(args)
  File "/usr/lib/python2.7/dist-packages/morituri/rip/cd.py", line 115, in do
    self.itable.getCDDBDiscId(), self.ittoc.getCDDBDiscId())
AssertionError: full table's id 7c1dc50a differs from toc id 7910ad0a
```

Can someone confirm this is related to the datatrack on MusicBrainz?

**Comment by butonic** [comment]
might ba a cdrdao problem:
```
$ cdrdao read-toc toto.toc
Cdrdao version 1.2.3 - (C) Andreas Mueller <andreas@daneb.de>
/dev/sr0: MATSHITA DVD-RAM UJ-820S	Rev: 1.20
Using driver: Generic SCSI-3/MMC - Version 2.0 (options 0x0000)

Reading toc data...

Track   Mode    Flags  Start                Length
------------------------------------------------------------
 1      AUDIO   0      00:00:00(     0)     08:23:01( 37726)
 2      AUDIO   0      08:23:01( 37726)     05:07:19( 23044)
 3      AUDIO   0      13:30:20( 60770)     08:17:03( 37278)
 4      AUDIO   0      21:47:23( 98048)     06:11:01( 27826)
 5      AUDIO   0      27:58:24(125874)     05:54:52( 26602)
 6      AUDIO   0      33:53:01(152476)     06:48:53( 30653)
 7      AUDIO   0      40:41:54(183129)     09:07:39( 41064)
 8      AUDIO   0      49:49:18(224193)     06:00:48( 27048)
 9      AUDIO   0      55:49:66(251241)     09:28:13( 42613)
10      AUDIO   0      65:18:04(293854)     05:51:50( 26375)
Leadout AUDIO   0      71:09:54(320229)

PQ sub-channel reading (audio track) is supported, data format is BCD.
Analyzing track 01 (AUDIO): start 00:00:00, length 08:23:01...
Found 12354 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 02 (AUDIO): start 08:23:01, length 05:07:19...
Found 7637 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 03 (AUDIO): start 13:30:20, length 08:17:03...
Found 12525 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 04 (AUDIO): start 21:47:23, length 06:11:01...
Found 9682 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 05 (AUDIO): start 27:58:24, length 05:54:52...
Found 8687 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 06 (AUDIO): start 33:53:01, length 06:48:53...
Found 9964 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 07 (AUDIO): start 40:41:54, length 09:07:39...
Found 13954 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 08 (AUDIO): start 49:49:18, length 06:00:48...
Found 9154 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 09 (AUDIO): start 55:49:66, length 09:28:13...
Found 448 Q sub-channels with CRC errors.
Found ISRC code.
Analyzing track 10 (AUDIO): start 65:18:04, length 05:51:50...
Found pre-gap: 65:20:04
Found 9000 Q sub-channels with CRC errors.
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Found CD-TEXT data.
        	
Reading of toc data finished successfully.
```

toto. toc contains
```
$ cat toto.toc
CD_DA

CD_TEXT {
  LANGUAGE_MAP {
    0: 9
  }
  LANGUAGE 0 {
    TITLE "Projekt Seerosenteich CD2"
    PERFORMER "Philipp Poisel"
    SIZE_INFO { 0,  1, 10,  0, 19, 14,  0,  0,  0,  0,  0,  0,
                0,  0,  0,  0,  0,  0,  0,  3, 35,  0,  0,  0,
                0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0}
  }
}

// Track 1
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "T00000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Z\374nde alle Feuer"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 0 08:23:01


// Track 2
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "X00000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Ich und Du"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 08:23:01 05:07:19


// Track 3
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "L00000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Hab keine Angst"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 13:30:20 08:17:03


// Track 4
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "800000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Wie soll ein Mensch das ertragen"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 21:47:23 06:11:01


// Track 5
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "D00000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Mit jedem deiner Fehler"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 27:58:24 05:54:52


// Track 6
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "H00000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Durch die Nacht"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 33:53:01 06:48:53


// Track 7
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "400000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Bis nach Toulouse"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 40:41:54 09:07:39


// Track 8
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "800000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Zwischen innen und au\337en"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 49:49:18 06:00:48


// Track 9
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "P00000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Als g\344b's kein Morgen mehr"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 55:49:66 00:00:00


// Track 10
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "T00000000000"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Ich will nur"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 0 71:11:54
START 65:20:04
```

**Comment by butonic** [comment]
old issue at http://thomas.apestaart.org/morituri/trac/ticket/22

**Comment by butonic** [comment]
looking at the cdrdao driver table and testing with setting the driver to plextor for my MATSHITA DVD-RAM UJ-820S  Rev: 1.20 i get a nicer result:
```
$ cdrdao read-toc --driver plextor toto-plex.toc                                                                                  ⏎
Cdrdao version 1.2.3 - (C) Andreas Mueller <andreas@daneb.de>
/dev/sr0: MATSHITA DVD-RAM UJ-820S	Rev: 1.20
Using driver: Plextor CD-ROM Reader - Version 1.3 (options 0x0000)

Reading toc data...

Track   Mode    Flags  Start                Length
------------------------------------------------------------
 1      AUDIO   0      00:00:00(     0)     08:23:01( 37726)
 2      AUDIO   0      08:23:01( 37726)     05:07:19( 23044)
 3      AUDIO   0      13:30:20( 60770)     08:17:03( 37278)
 4      AUDIO   0      21:47:23( 98048)     06:11:01( 27826)
 5      AUDIO   0      27:58:24(125874)     05:54:52( 26602)
 6      AUDIO   0      33:53:01(152476)     06:48:53( 30653)
 7      AUDIO   0      40:41:54(183129)     09:07:39( 41064)
 8      AUDIO   0      49:49:18(224193)     06:00:48( 27048)
 9      AUDIO   0      55:49:66(251241)     09:28:13( 42613)
10      AUDIO   0      65:18:04(293854)     05:51:50( 26375)
Leadout AUDIO   0      71:09:54(320229)

Analyzing track 01 (AUDIO): start 00:00:00, length 08:23:01...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 02 (AUDIO): start 08:23:01, length 05:07:19...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 03 (AUDIO): start 13:30:20, length 08:17:03...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 04 (AUDIO): start 21:47:23, length 06:11:01...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 05 (AUDIO): start 27:58:24, length 05:54:52...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 06 (AUDIO): start 33:53:01, length 06:48:53...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 07 (AUDIO): start 40:41:54, length 09:07:39...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 08 (AUDIO): start 49:49:18, length 06:00:48...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 09 (AUDIO): start 55:49:66, length 09:28:13...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Analyzing track 10 (AUDIO): start 65:18:04, length 05:51:50...
Found ISRC code.
Control nibbles of track match CD-TOC settings.
Found CD-TEXT data.
        	
Reading of toc data finished successfully.
```
$ cat toto-plex.toc
CD_DA

CD_TEXT {
  LANGUAGE_MAP {
    0: 9
  }
  LANGUAGE 0 {
    TITLE "Projekt Seerosenteich CD2"
    PERFORMER "Philipp Poisel"
    SIZE_INFO { 0,  1, 10,  0, 19, 14,  0,  0,  0,  0,  0,  0,
                0,  0,  0,  0,  0,  0,  0,  3, 35,  0,  0,  0,
                0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0}
  }
}

// Track 1
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200366"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Z\374nde alle Feuer"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 0 08:23:01


// Track 2
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200367"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Ich und Du"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 08:23:01 05:07:19


// Track 3
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200368"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Hab keine Angst"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 13:30:20 08:17:03


// Track 4
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200369"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Wie soll ein Mensch das ertragen"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 21:47:23 06:11:01


// Track 5
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200370"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Mit jedem deiner Fehler"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 27:58:24 05:54:52


// Track 6
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200371"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Durch die Nacht"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 33:53:01 06:48:53


// Track 7
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200372"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Bis nach Toulouse"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 40:41:54 09:07:39


// Track 8
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200373"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Zwischen innen und au\337en"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 49:49:18 06:00:48


// Track 9
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200374"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Als g\344b's kein Morgen mehr"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 55:49:66 09:28:13


// Track 10
TRACK AUDIO
NO COPY
NO PRE_EMPHASIS
TWO_CHANNEL_AUDIO
ISRC "GBLAZ1200375"
CD_TEXT {
  LANGUAGE 0 {
    TITLE "Ich will nur"
    PERFORMER "Philipp Poisel"
  }
}
FILE "data.wav" 65:18:04 05:51:50
```

**Comment by RankoKohime** [comment]
Has there been any update on this issue, or possibly a workaround?

**Comment by ArchangeGabriel** [comment]
@RankoKohime There is ongoing investigation at https://github.com/JoeLametta/whipper/issues/72 (whipper is a morituri fork due to @thomasvs apparent inactivity here). The bug seems to lie in cdrdao, maybe if you provide the same kind of information that the other person did there this might revive this issue and help the devs found the culprit and fix this. ;)
